// =============================================================
// services/reportGenerator.ts
// Generates a downloadable PDF portfolio report
// Uses jsPDF (lightweight, no server needed)
// Premium feature — called from Account page or Investment Hub
// =============================================================

// This service creates a polished PDF portfolio report with:
// - Cover page with myfynzo branding
// - Portfolio summary (total value, cost, P&L, allocation)
// - Per-holding breakdown with performance
// - Wealth projection summary
// - Expense summary
// - Goals progress

export interface ReportData {
  userName: string;
  currency: string;
  country: string;
  date: string;
  // Portfolio
  investments: {
    name: string; type: string; symbol: string;
    quantity: number; purchasePrice: number; currentPrice: number;
    purchaseDate: string; gain: number; gainPct: number;
  }[];
  totalValue: number;
  totalCost: number;
  totalGain: number;
  totalGainPct: number;
  // Recurring
  recurringInvestments: { name: string; monthlyAmount: number; category: string }[];
  totalMonthlyInvestment: number;
  // Cash & Assets
  cashSavings: number;
  physicalAssets: number;
  // Debts
  totalDebt: number;
  debts: { name: string; remaining: number; rate: number; monthly: number }[];
  // Net Worth
  netWorth: number;
  // Expenses
  monthlyExpenses: number;
  annualExpenses: number;
  // Goals
  goals: { name: string; target: number; current: number; progress: number }[];
  // Projection
  projectedValue: number;
  projectionYears: number;
  expectedReturn: number;
  // Allocation
  allocationByType: { type: string; value: number; pct: number }[];
}

export async function generatePortfolioReport(data: ReportData): Promise<Blob> {
  // Dynamic import — jsPDF is only loaded when user requests a report
  const { jsPDF } = await import('jspdf');

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const W = 210, H = 297;
  const margin = 20;
  const contentW = W - margin * 2;
  let y = margin;

  const PRIMARY = [13, 148, 136]; // teal-600
  const SECONDARY = [30, 41, 59]; // slate-800
  const GRAY = [148, 163, 184]; // slate-400
  const GREEN = [16, 185, 129];
  const RED = [239, 68, 68];

  const fmt = (n: number) => {
    const sym = data.currency === 'INR' ? '₹' : data.currency === 'EUR' ? '€' : '$';
    if (Math.abs(n) >= 100000 && data.currency === 'INR') {
      return `${sym}${(n / 100000).toFixed(2)}L`;
    }
    return `${sym}${n.toLocaleString('en', { maximumFractionDigits: 0 })}`;
  };

  // ═══ COVER PAGE ═══
  // Background gradient (simulated with rectangles)
  doc.setFillColor(30, 41, 59);
  doc.rect(0, 0, W, H, 'F');

  // Accent bar
  doc.setFillColor(...PRIMARY);
  doc.rect(0, 0, W, 4, 'F');

  // Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(36);
  doc.setTextColor(255, 255, 255);
  doc.text('Portfolio Report', margin, 80);

  doc.setFontSize(14);
  doc.setTextColor(148, 163, 184);
  doc.text(data.userName, margin, 95);
  doc.text(data.date, margin, 105);

  // Key metrics on cover
  doc.setFontSize(11);
  doc.setTextColor(148, 163, 184);
  const coverMetrics = [
    { label: 'Net Worth', value: fmt(data.netWorth) },
    { label: 'Portfolio Value', value: fmt(data.totalValue) },
    { label: 'Total P&L', value: `${data.totalGain >= 0 ? '+' : ''}${fmt(data.totalGain)} (${data.totalGainPct >= 0 ? '+' : ''}${data.totalGainPct.toFixed(1)}%)` },
    { label: 'Monthly Investment', value: fmt(data.totalMonthlyInvestment) },
    { label: `Projected (${data.projectionYears}yr)`, value: fmt(data.projectedValue) },
  ];

  let cy = 140;
  coverMetrics.forEach(m => {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(148, 163, 184);
    doc.text(m.label, margin, cy);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.setTextColor(255, 255, 255);
    doc.text(m.value, margin, cy + 8);
    cy += 22;
  });

  // Footer
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text('Generated by myfynzo — AI-Powered Wealth Management', margin, H - 20);
  doc.text('myfynzo.com', margin, H - 14);

  // ═══ PAGE 2: PORTFOLIO SUMMARY ═══
  doc.addPage();
  y = margin;

  // Header
  doc.setFillColor(...PRIMARY);
  doc.rect(0, 0, W, 3, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(...SECONDARY);
  doc.text('Portfolio Summary', margin, y + 15);
  y += 25;

  // Summary cards row
  const cardData = [
    { label: 'Total Value', value: fmt(data.totalValue), sub: `${data.investments.length} holdings` },
    { label: 'Total Cost', value: fmt(data.totalCost), sub: 'Cost basis' },
    { label: 'Total P&L', value: `${data.totalGain >= 0 ? '+' : ''}${fmt(data.totalGain)}`, sub: `${data.totalGainPct >= 0 ? '+' : ''}${data.totalGainPct.toFixed(1)}%`, color: data.totalGain >= 0 ? GREEN : RED },
    { label: 'Cash & Savings', value: fmt(data.cashSavings), sub: '' },
  ];

  const cardW = (contentW - 12) / 4;
  cardData.forEach((card, i) => {
    const cx = margin + i * (cardW + 4);
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(cx, y, cardW, 28, 2, 2, 'F');
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(...GRAY);
    doc.text(card.label, cx + 4, y + 8);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(...(card.color || SECONDARY));
    doc.text(card.value, cx + 4, y + 17);
    if (card.sub) {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(6);
      doc.setTextColor(...GRAY);
      doc.text(card.sub, cx + 4, y + 23);
    }
  });
  y += 38;

  // Allocation table
  if (data.allocationByType.length > 0) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(...SECONDARY);
    doc.text('Asset Allocation', margin, y);
    y += 8;

    // Bar visualization
    const barH = 8;
    const colors = [[13,148,136], [59,130,246], [245,158,11], [168,85,247], [239,68,68], [107,114,128]];
    let barX = margin;
    data.allocationByType.forEach((a, i) => {
      const barW = (a.pct / 100) * contentW;
      doc.setFillColor(...(colors[i % colors.length] as [number, number, number]));
      doc.rect(barX, y, Math.max(barW, 1), barH, 'F');
      barX += barW;
    });
    y += barH + 5;

    // Legend
    data.allocationByType.forEach((a, i) => {
      doc.setFillColor(...(colors[i % colors.length] as [number, number, number]));
      doc.circle(margin + 2, y + 1.5, 1.5, 'F');
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(...SECONDARY);
      doc.text(`${a.type}: ${fmt(a.value)} (${a.pct.toFixed(1)}%)`, margin + 7, y + 3);
      y += 6;
    });
    y += 6;
  }

  // Holdings table
  if (data.investments.length > 0) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(...SECONDARY);
    doc.text('Holdings', margin, y);
    y += 6;

    // Table header
    doc.setFillColor(241, 245, 249);
    doc.rect(margin, y, contentW, 7, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7);
    doc.setTextColor(...GRAY);
    doc.text('Name', margin + 2, y + 5);
    doc.text('Type', margin + 55, y + 5);
    doc.text('Qty', margin + 80, y + 5);
    doc.text('Avg Price', margin + 95, y + 5);
    doc.text('Current', margin + 118, y + 5);
    doc.text('Value', margin + 138, y + 5);
    doc.text('P&L', margin + 158, y + 5);
    y += 9;

    // Table rows
    const sorted = [...data.investments].sort((a, b) => (b.quantity * b.currentPrice) - (a.quantity * a.currentPrice));
    sorted.slice(0, 25).forEach((inv, i) => {
      if (y > H - 30) { doc.addPage(); y = margin + 10; }
      if (i % 2 === 0) {
        doc.setFillColor(248, 250, 252);
        doc.rect(margin, y - 3, contentW, 7, 'F');
      }
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7);
      doc.setTextColor(...SECONDARY);
      doc.text(inv.name.slice(0, 30), margin + 2, y + 1);
      doc.setTextColor(...GRAY);
      doc.text(inv.type.slice(0, 12), margin + 55, y + 1);
      doc.text(String(inv.quantity), margin + 80, y + 1);
      doc.text(fmt(inv.purchasePrice), margin + 95, y + 1);
      doc.text(fmt(inv.currentPrice), margin + 118, y + 1);
      doc.setTextColor(...SECONDARY);
      doc.text(fmt(inv.quantity * inv.currentPrice), margin + 138, y + 1);
      doc.setTextColor(...(inv.gain >= 0 ? GREEN : RED));
      doc.text(`${inv.gain >= 0 ? '+' : ''}${inv.gainPct.toFixed(1)}%`, margin + 158, y + 1);
      y += 7;
    });
    y += 6;
  }

  // ═══ PAGE 3: FINANCIAL OVERVIEW ═══
  if (y > H - 80) { doc.addPage(); y = margin + 10; }

  // Goals
  if (data.goals.length > 0) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(...SECONDARY);
    doc.text('Goals Progress', margin, y);
    y += 8;

    data.goals.forEach(goal => {
      if (y > H - 25) { doc.addPage(); y = margin + 10; }
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(...SECONDARY);
      doc.text(`${goal.name}`, margin, y + 3);
      doc.text(`${fmt(goal.current)} / ${fmt(goal.target)}`, margin + 90, y + 3);
      doc.text(`${goal.progress}%`, margin + 155, y + 3);

      // Progress bar
      doc.setFillColor(226, 232, 240);
      doc.roundedRect(margin, y + 6, contentW, 3, 1, 1, 'F');
      doc.setFillColor(...PRIMARY);
      doc.roundedRect(margin, y + 6, Math.max(contentW * (goal.progress / 100), 2), 3, 1, 1, 'F');
      y += 14;
    });
    y += 6;
  }

  // Debts
  if (data.debts.length > 0) {
    if (y > H - 50) { doc.addPage(); y = margin + 10; }
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(...SECONDARY);
    doc.text('Debts', margin, y);
    y += 8;

    data.debts.forEach(debt => {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(...SECONDARY);
      doc.text(debt.name, margin, y + 3);
      doc.text(`${fmt(debt.remaining)} remaining`, margin + 60, y + 3);
      doc.text(`${debt.rate}% APR`, margin + 110, y + 3);
      doc.text(`${fmt(debt.monthly)}/mo`, margin + 145, y + 3);
      y += 7;
    });
    y += 6;
  }

  // Net Worth Summary
  if (y > H - 50) { doc.addPage(); y = margin + 10; }
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(...SECONDARY);
  doc.text('Net Worth Breakdown', margin, y);
  y += 8;

  const nwItems = [
    { label: 'Investments', value: data.totalValue },
    { label: 'Cash & Savings', value: data.cashSavings },
    { label: 'Physical Assets', value: data.physicalAssets },
    { label: 'Debts', value: -data.totalDebt },
    { label: 'NET WORTH', value: data.netWorth, bold: true },
  ];

  nwItems.forEach(item => {
    const isBold = (item as any).bold;
    if (isBold) {
      doc.setDrawColor(...PRIMARY);
      doc.line(margin, y - 1, margin + contentW, y - 1);
      y += 2;
    }
    doc.setFont('helvetica', isBold ? 'bold' : 'normal');
    doc.setFontSize(isBold ? 10 : 8);
    doc.setTextColor(...SECONDARY);
    doc.text(item.label, margin, y + 3);
    doc.setTextColor(...(item.value >= 0 ? SECONDARY : RED));
    doc.text(fmt(item.value), margin + contentW - 2, y + 3, { align: 'right' });
    y += isBold ? 10 : 7;
  });

  // Footer on last page
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(7);
  doc.setTextColor(...GRAY);
  doc.text('This report is for informational purposes only and does not constitute financial advice.', margin, H - 20);
  doc.text(`Generated by myfynzo on ${data.date} — myfynzo.com`, margin, H - 14);

  return doc.output('blob');
}
